### PR TITLE
Remove Microsoft.Windows.Compatibility

### LINKED ISSUE #266: .NET Core shouldn't use Microsoft.Windows.Compatibility
Just include whatever is necessary, the Microsoft.Windows.Compatibility contains a ton of unused stuff (e.g. the sni.dlls of SqlClient).
Also applies to the XAMLMarkupExtensions project.

### PR DESCRIPTION
**Pull request by Phyxion**
Fixes #266.

### CODE REVIEW

**Comment by Phyxion** [comment]
It builds just fine despite the error.

**Comment by konne** [comment]
no issue with the compile error. i will take care
thx for contribution

**Comment by konne** [comment]
@Phyxion please fix, the PR have to be against the dev branch

**Comment by Phyxion** [comment]
Opened new PR, closing this.

**Pull request closed without merging**
