### PR TITLE
Remove WeakReference.IsAlive usage

### PR DESCRIPTION
**Pull request by xmedeko**
Fix NRE in ParentChangedNotifier.Remove.

The `WeakReference.IsAlive` [should not be used](https://docs.microsoft.com/en-us/dotnet/api/system.weakreference.isalive). Safe pattern is: make a local copy, compare it to `null`. I've left the `IsAlive` check in the `TypedWeakReference` because the `T` is not restricted to class. We may restrict it to class and then remove the `IsAlive` check, too.

Note: I have rare crash reports of our app:
```
Thread UnhandledException System.NullReferenceException: Object reference not set to an instance of an object. at WPFLocalizeExtension.Engine.ParentNotifiers.Remove(DependencyObject target)
at WPFLocalizeExtension.Providers.ParentChangedNotifierHelper.GetValueOrRegisterParentNotifier[T](DependencyObject target, Func`2 getFunction, Action`1 parentChangedAction, ParentNotifiers parentNotifiers)
at WPFLocalizeExtension.Providers.ParentChangedNotifierHelper.GetValueOrRegisterParentNotifier[T](DependencyObject target, DependencyProperty property, Action`1 parentChangedAction, ParentNotifiers parentNotifiers)
at WPFLocalizeExtension.Providers.ResxLocalizationProvider.GetDictionary(DependencyObject target) at WPFLocalizeExtension.Providers.ResxLocalizationProviderBase.GetFullyQualifiedResourceKey(String key, DependencyObject target)
at VirtualTraining.Container.VTResxLocalizationProvider.GetFullyQualifiedResourceKey(String key, DependencyObject target) in C:\bamboo\build\VT-WIN7-JOB1\code\VirtualTraining\Container\WPFLocalizeExtensionConfig.cs:line 53
at WPFLocalizeExtension.Engine.LocalizeDictionary.GetFullyQualifiedResourceKey(String key, DependencyObject target, ILocalizationProvider provider)
at WPFLocalizeExtension.Engine.LocalizeDictionary.GetFullyQualifiedResourceKey(String key, DependencyObject target) at WPFLocalizeExtension.Extensions.LocExtension.FormatOutput(TargetInfo endPoint, TargetInfo info)
at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath) in C:\OWN\SCM-Store\GitHub\MrCircuit\XAMLMarkupExtensions\XAMLMarkupExtensions\Base\NestedMarkupExtension.cs:line 398
at XAMLMarkupExtensions.Base.NestedMarkupExtension.OnEndpointReached(NestedMarkupExtension sender, EndpointReachedEventArgs args) in C:\OWN\SCM-Store\GitHub\MrCircuit\XAMLMarkupExtensions\XAMLMarkupExtensions\Base\NestedMarkupExtension.cs:line 585 
```

### CODE REVIEW

**Comment by SeriousM** [comment]
looks good to me

**Comment by konne** [comment]
@xmedeko thank for you PR, I like to get deeper into the changes, because you do a little bit more than make a copy before checking IsAlive. I try to go through this week

**Comment by xmedeko** [comment]
Yes, I have removed useless check `ContainsKey` before `Remove`, because `Remove` does the check, too. And a bit of RFCT of `Remove`.
I see I have commited also nuget update of `WPFLocalizationExtensionDemoApplication`, sorry. I may remove it from PR.

**Comment by xmedeko** [comment]
@konne do you have time to look at this PR? Should I clean the commit? Thanks.

**Comment by konne** [comment]
@xmedeko I just wait on https://github.com/XAMLMarkupExtensions/XAMLMarkupExtensions/issues/30 this nuget test and will merge after that your pr and update the dependencies and will than release a new nuget from this repo

**Comment by konne** [comment]
@xmedeko a new prerelease Nuget is online please test. If there is no issues in the next week I will generate a release WPFLocalizeExtension.3.4.0-alpha0016.nupkg

**Comment by xmedeko** [comment]
Thanks for the merge.
Test of common operation with 3.4.0-alpha0016 is OK.

**Pull request merged**
