### PR TITLE
Feature/enable mvvm bindings

### PR DESCRIPTION
**Pull request by sa-he**
https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/issues/117

I've introduced 

- BindingLoc which works fine as long as you do not want to set it in a style
- TranslateConverter + ResourceKeyViewModel which is not as compfortable, but also working in a style

I'va extended the demo application to show how it can be used

### CODE REVIEW

**Comment by konne** [comment]
@SchwabenProgger thanks for you contribution, but you have to wait a little bit.
I really like to finish the current XAMLExtension issue and like to add PublicSigned DLL. After that I will take care of this. If you are in Germany I really like to have a short conversation to make a short CodeReview first in a call.

**Comment by SchwabenProgger** [comment]
We sure can do a code review, I do speak German. Just come back to me once you are ready..

**Comment by konne** [comment]
@SchwabenProgger sorry, I complete removed that example, part of this example was also in the tests.
So this breaks your PR. I will move in the next days some simple Examples like HelloWord,... from tests to examples and after that we should have a short call to get your contribution fast into the main line.

**Comment by konne** [comment]
@sa-he please can you ping me. Do we have a change this week to have a skype call about that PR.
I'm at the moment much more active and try to cleanup a lot of open issues in the next weeks.

**Comment by konne** [comment]
@sa-he I added a first draft into the new branch feature/mvvm4loc
I have at the moment some designtime issues but this was already working in the beginning and I will fix it. Please have a look at the HelloWorldWPF sample.
I will still let this PR open until I moved style tests in a new sample app. Please have a look and give feedback

**Comment by sa-he** [comment]
Your approach to include it in the existing LocExtension is less confusing for consumers than creating a new extension. Nice. But keep in mind that it is not working in a style. 

In order to make that possible, I introduced `TranslateConverter` and `ResourceKeyViewModel`. Maybe there is a way to incorporate this functionality in BLoc? That'd be the most intuitive way for consumers.

**Comment by konne** [comment]
@sa-he I have it in mind that this is not working in a style. This is the reason why I also let this PR open. I will close it only if all your feature request are implemented and working.

The other big advantage of my current solution ist that the binding is fully usable, even you can attach your own Converter into the binding.

**Comment by konne** [comment]
@sa-he I  had a deep dive into all the issues of wpf binding / setters and co. The issue behind is that the Binding class is on important methods sealed, internal,...
On the other side the Setter expliziet expects a Markup of BindingBase or DynamicResource and nothing else.
Be honest I don't like the ResourceKeyViewModel. My best solution for now would be:

```xml
<Setter Property="Text" >
    <Setter.Value>
        <MultiBinding Converter="{StaticResource TranslateConverter}">
            <Binding Path="language" FallbackValue="de" />
            <Binding Source="{x:Static lex:LocalizeDictionary.Instance}" Path="Culture"/>
        </MultiBinding> 
    </Setter.Value>
</Setter>
```

I know that this code is not optimal and a little bit strange why to add this language as the second binding, but it complete solves all binding update issues, even without a special markupextension. 
You only need this MultiValueConverter.

What do you think?

**Comment by konne** [comment]
I will close this PR now and deliver the new functionality in a first preRelease

**Pull request closed without merging**
