### PR TITLE
mark WeakRef class only for NET35, fix code issues for GenericWeakRef…

### PR DESCRIPTION
**Pull request by konne**
…erence usage

### CODE REVIEW

**Comment by konne** [comment]
@SeriousM @xmedeko  please have a look at this PR.
I like to use the real WeakReference<T> class in all .NET >=45 and have no reduced the usage of the TypeWeakReference class only for a compatibilty layer for NET35. Because the WeakReference<T> has no Target I had to make some small changes.
After this is okay I like to "upgrade" the WeakReference in the LocalizedDictionary also to the Type Version.

**Comment by SeriousM** [comment]
Looks good to me :)

**Comment by xmedeko** [comment]
`TryGetTarget` is not well. When using weak reference, always make it strong first and then use your strong reference. Do not use `base.Target` then. It may become garbage collected just before you use it. 
Also, the `IsAlive` check is redundant. (`WeakReference.IsAlive` is almost always useless.) So I suggest:
```c#
public bool TryGetTarget(out T target)
    var baseTarget = base.Target;
    if (baseTarget != null)
    {
        target = (T)baseTarget ;
        return true;
    }
    target = default(T);
    return false;
}
```

Also, rename file `TypedWeakReference.cs` -> `WeakReference.cs`.

**Comment by konne** [comment]
@xmedeko thanks, I changed it and will merge it

**Pull request merged**
